# application.properties
db.url=jdbc:h2:mem:quantity_db;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:db/schema.sql'
db.username=sa
db.password=
db.pool.maxConnections=10
db.pool.minIdle=2
db.pool.idleTimeoutMs=30000

# application configs
app.repository.type=DATABASE # can be CACHE or DATABASE
